### ISSUE TITLE
Doesn't register properly with certain launchers, false double-mod issue!

### ISSUE THREAD

**Issue by Ski-z** [Itskillerluc/gtfo_craft#49]
Hey there! Great mod, however there is a serious issue when using some 3rd party launchers ([like GDLauncher](https://gdlauncher.com/)).

Upon loading with these launchers, a bug makes the game believe there are two versions within the mod folder registered.

This is an infrequent but not unheard of issue I've had multiple mod authors fix with their mods. I hope you will, too!

Here's one example: https://github.com/AHilyard/EquipmentCompare/issues/16 this was fixed

Here's another example: https://github.com/someaddons/farsight/issues/67#issuecomment-1688032515 this was fixed too

THIS is the most important one. You must add some like to the build.gradle file:

https://github.com/SkpC9/Normal-Damage/issues/1#issuecomment-1672167568

Please give this a look!

**Comment by Lvgraef** [comment]
I think I might have fixed the issue.
Could you please test the following jar file and let me know if it works.
If it works I will upload it to curseforge.
[GTFO Craft Protocol-1.0.1.zip](https://github.com/Itskillerluc/gtfo_craft/files/14026639/GTFO.Craft.Protocol-1.0.1.zip)

**Comment by Ski-z** [comment]
Yes that fixed it! Thank you!

**Comment by Lvgraef** [comment]
Great, it should be on curseforge soon too! Thank you for the report and reasearch!
